name: Rust CI

on:
  # workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

# 3rd-party actions are referred to with a full-length commit SHA:
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions

jobs:
  build:
    name: Yolo!
    runs-on: rust:1.76.0-slim-bullseye
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2, 2023-04-13

      # - name: Setup Rust cache
      #   uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # 2.7.0 

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        run: cargo test --all-targets
